/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wecount.View;

import javax.swing.JOptionPane;
import wecount.Controller.FungsiControl;
import wecount.Controller.TableControl;

/**
 *
 * @author Lenovo
 */
public class ViewAdmin extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    public ViewAdmin() {
        initComponents();
        setLocationRelativeTo(null);
        tbListPenyewa.setModel(tc.getModelPenyewa());
        tbListLapak.setModel(tc.getModelLapak());
        tbListTransaksi.setModel(tc.getModelTransaksi());
            tbListToko.setModel(tc.getModelToko());
        tc.loadKolomTransaksi();
        tc.loadKolomPenyewa();
        tc.loadKolomLapak();
        tc.loadKolomToko();
        tc.loadToko();
        tc.showToko();
    }
    
    FungsiControl fc = new FungsiControl();
    TableControl tc = new TableControl();
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnListToko = new javax.swing.JButton();
        btnListLapak = new javax.swing.JButton();
        btnListPenyewa = new javax.swing.JButton();
        btnListTransaksi = new javax.swing.JButton();
        btnPengaturan1 = new javax.swing.JButton();
        adminPanel = new javax.swing.JPanel();
        listToko = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbListToko = new javax.swing.JTable();
        listLapak = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbListLapak = new javax.swing.JTable();
        tambahLapak = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfUkuranPanjang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfHargaLapak = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btTambahLapak = new javax.swing.JButton();
        tfUkuranLebar = new javax.swing.JTextField();
        cbLokasiLapak = new javax.swing.JComboBox<>();
        editLapak = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tfEditPanjang = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tfEditHarga = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        btUbahLapak = new javax.swing.JButton();
        tfEditLebar = new javax.swing.JTextField();
        etcbLokasiLapak = new javax.swing.JComboBox<>();
        listPenyewa = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbListPenyewa = new javax.swing.JTable();
        listTransaksi = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbListTransaksi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidePanel.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HELLO ADMIN");

        btnListToko.setBackground(new java.awt.Color(51, 51, 51));
        btnListToko.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnListToko.setForeground(new java.awt.Color(204, 204, 204));
        btnListToko.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wecount/View/Screenshot (87).png"))); // NOI18N
        btnListToko.setText("List Toko");
        btnListToko.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnListToko.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/wecount/View/Screenshot (87) - Copy.png"))); // NOI18N
        btnListToko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListTokoActionPerformed(evt);
            }
        });

        btnListLapak.setBackground(new java.awt.Color(51, 51, 51));
        btnListLapak.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnListLapak.setForeground(new java.awt.Color(204, 204, 204));
        btnListLapak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wecount/View/Screenshot (87).png"))); // NOI18N
        btnListLapak.setText("List Lapak");
        btnListLapak.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnListLapak.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/wecount/View/Screenshot (87) - Copy.png"))); // NOI18N
        btnListLapak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListLapakActionPerformed(evt);
            }
        });

        btnListPenyewa.setBackground(new java.awt.Color(51, 51, 51));
        btnListPenyewa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnListPenyewa.setForeground(new java.awt.Color(204, 204, 204));
        btnListPenyewa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wecount/View/Screenshot (87).png"))); // NOI18N
        btnListPenyewa.setText("List Penyewa");
        btnListPenyewa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnListPenyewa.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/wecount/View/Screenshot (87) - Copy.png"))); // NOI18N
        btnListPenyewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListPenyewaActionPerformed(evt);
            }
        });

        btnListTransaksi.setBackground(new java.awt.Color(51, 51, 51));
        btnListTransaksi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnListTransaksi.setForeground(new java.awt.Color(204, 204, 204));
        btnListTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wecount/View/Screenshot (87).png"))); // NOI18N
        btnListTransaksi.setText("List Transaksi");
        btnListTransaksi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnListTransaksi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/wecount/View/Screenshot (87) - Copy.png"))); // NOI18N
        btnListTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListTransaksiActionPerformed(evt);
            }
        });

        btnPengaturan1.setBackground(new java.awt.Color(51, 51, 51));
        btnPengaturan1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPengaturan1.setForeground(new java.awt.Color(255, 255, 255));
        btnPengaturan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wecount/View/Screenshot (87) - Copy.png"))); // NOI18N
        btnPengaturan1.setText("LOG OUT");
        btnPengaturan1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPengaturan1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/wecount/View/Screenshot (87).png"))); // NOI18N
        btnPengaturan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengaturan1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListToko, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnListLapak, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnListPenyewa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnListTransaksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnPengaturan1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnListToko, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListLapak, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListPenyewa, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnPengaturan1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        adminPanel.setBackground(new java.awt.Color(51, 51, 51));
        adminPanel.setLayout(new java.awt.CardLayout());

        listToko.setBackground(new java.awt.Color(0, 102, 102));

        jLabel28.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("LIST TOKO");

        jScrollPane6.setBackground(new java.awt.Color(0, 102, 102));

        tbListToko.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tbListToko.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Toko", "ID Penyewa", "Nama Toko", "Lokasi ", "Ukuran", "Harga Sewa", "Status Bayar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tbListToko);

        javax.swing.GroupLayout listTokoLayout = new javax.swing.GroupLayout(listToko);
        listToko.setLayout(listTokoLayout);
        listTokoLayout.setHorizontalGroup(
            listTokoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listTokoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(listTokoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        listTokoLayout.setVerticalGroup(
            listTokoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listTokoLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );

        adminPanel.add(listToko, "card5");

        listLapak.setBackground(new java.awt.Color(0, 102, 102));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LIST LAPAK");

        tbListLapak.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lokasi", "Ukuran", "Harga Sewa", "Status", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbListLapak);

        tambahLapak.setBackground(new java.awt.Color(0, 102, 102));
        tambahLapak.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TAMBAH LAPAK", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lokasi Lapak");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ukuran");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Harga Sewa");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Rp.");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("x");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("meter");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("/ Tahun");

        btTambahLapak.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btTambahLapak.setForeground(new java.awt.Color(255, 255, 255));
        btTambahLapak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wecount/View/Screenshot (87) - Copy.png"))); // NOI18N
        btTambahLapak.setText("Tambahkan");
        btTambahLapak.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btTambahLapak.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/wecount/View/Screenshot (87).png"))); // NOI18N
        btTambahLapak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambahLapakActionPerformed(evt);
            }
        });

        cbLokasiLapak.setEditable(true);
        cbLokasiLapak.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbLokasiLapak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A1", "A2", "A3", "A4" }));
        cbLokasiLapak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLokasiLapakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tambahLapakLayout = new javax.swing.GroupLayout(tambahLapak);
        tambahLapak.setLayout(tambahLapakLayout);
        tambahLapakLayout.setHorizontalGroup(
            tambahLapakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahLapakLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahLapakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahLapakLayout.createSequentialGroup()
                        .addGroup(tambahLapakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tambahLapakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tambahLapakLayout.createSequentialGroup()
                                .addGroup(tambahLapakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                    .addComponent(tfUkuranPanjang))
                                .addGroup(tambahLapakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tambahLapakLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(tfHargaLapak, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(tambahLapakLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfUkuranLebar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(cbLokasiLapak, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btTambahLapak, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        tambahLapakLayout.setVerticalGroup(
            tambahLapakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahLapakLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahLapakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbLokasiLapak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tambahLapakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUkuranPanjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jLabel6)
                    .addComponent(tfUkuranLebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tambahLapakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfHargaLapak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(btTambahLapak, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editLapak.setBackground(new java.awt.Color(0, 102, 102));
        editLapak.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EDIT LAPAK", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Lokasi Lapak");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ukuran");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Harga Sewa");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Rp.");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("x");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("meter");

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("/ Tahun");

        btUbahLapak.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btUbahLapak.setForeground(new java.awt.Color(255, 255, 255));
        btUbahLapak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wecount/View/Screenshot (87) - Copy.png"))); // NOI18N
        btUbahLapak.setText("Ubah");
        btUbahLapak.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btUbahLapak.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/wecount/View/Screenshot (87).png"))); // NOI18N
        btUbahLapak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUbahLapakActionPerformed(evt);
            }
        });

        etcbLokasiLapak.setEditable(true);
        etcbLokasiLapak.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        etcbLokasiLapak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A1", "A2", "A3", "A4" }));
        etcbLokasiLapak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etcbLokasiLapakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editLapakLayout = new javax.swing.GroupLayout(editLapak);
        editLapak.setLayout(editLapakLayout);
        editLapakLayout.setHorizontalGroup(
            editLapakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editLapakLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editLapakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editLapakLayout.createSequentialGroup()
                        .addGroup(editLapakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editLapakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editLapakLayout.createSequentialGroup()
                                .addGroup(editLapakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                    .addComponent(tfEditPanjang))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(editLapakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(editLapakLayout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfEditLebar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(editLapakLayout.createSequentialGroup()
                                        .addComponent(tfEditHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(etcbLokasiLapak, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btUbahLapak, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        editLapakLayout.setVerticalGroup(
            editLapakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editLapakLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editLapakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(etcbLokasiLapak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(editLapakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEditPanjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel14)
                    .addComponent(tfEditLebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editLapakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tfEditHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addComponent(btUbahLapak, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout listLapakLayout = new javax.swing.GroupLayout(listLapak);
        listLapak.setLayout(listLapakLayout);
        listLapakLayout.setHorizontalGroup(
            listLapakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listLapakLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(listLapakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(listLapakLayout.createSequentialGroup()
                        .addGroup(listLapakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(listLapakLayout.createSequentialGroup()
                                .addComponent(tambahLapak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(editLapak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(33, 33, 33))
        );
        listLapakLayout.setVerticalGroup(
            listLapakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listLapakLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(listLapakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editLapak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tambahLapak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(184, Short.MAX_VALUE))
        );

        adminPanel.add(listLapak, "card3");

        listPenyewa.setBackground(new java.awt.Color(0, 102, 102));

        jLabel29.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("LIST PENYEWA");

        jScrollPane7.setBackground(new java.awt.Color(0, 102, 102));

        tbListPenyewa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tbListPenyewa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Penyewa", "Username", "Nama Penyewa", "Alamat", "No Telp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tbListPenyewa);

        javax.swing.GroupLayout listPenyewaLayout = new javax.swing.GroupLayout(listPenyewa);
        listPenyewa.setLayout(listPenyewaLayout);
        listPenyewaLayout.setHorizontalGroup(
            listPenyewaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listPenyewaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(listPenyewaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        listPenyewaLayout.setVerticalGroup(
            listPenyewaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listPenyewaLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );

        adminPanel.add(listPenyewa, "card6");

        listTransaksi.setBackground(new java.awt.Color(0, 102, 102));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("LIST TRANSAKSI");

        jScrollPane4.setBackground(new java.awt.Color(0, 102, 102));

        tbListTransaksi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tbListTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tanggal", "Nama Toko", "Nama Penyewa", "Masukan", "Pengeluaran", "Pendapatan Awal", "Pendapatan Akhir"
            }
        ));
        jScrollPane4.setViewportView(tbListTransaksi);
        if (tbListTransaksi.getColumnModel().getColumnCount() > 0) {
            tbListTransaksi.getColumnModel().getColumn(4).setHeaderValue("Pengeluaran");
            tbListTransaksi.getColumnModel().getColumn(5).setHeaderValue("Pendapatan Awal");
            tbListTransaksi.getColumnModel().getColumn(6).setHeaderValue("Pendapatan Akhir");
        }

        javax.swing.GroupLayout listTransaksiLayout = new javax.swing.GroupLayout(listTransaksi);
        listTransaksi.setLayout(listTransaksiLayout);
        listTransaksiLayout.setHorizontalGroup(
            listTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listTransaksiLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(listTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        listTransaksiLayout.setVerticalGroup(
            listTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listTransaksiLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );

        adminPanel.add(listTransaksi, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(adminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnListTokoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListTokoActionPerformed
        // TODO add your handling code here:
        adminPanel.removeAll();
        adminPanel.repaint();
        adminPanel.revalidate();

        adminPanel.add(listToko);
        adminPanel.repaint();
        adminPanel.revalidate();
        
        tc.loadToko();
        tc.showToko();
    }//GEN-LAST:event_btnListTokoActionPerformed

    private void btnListLapakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListLapakActionPerformed
        // TODO add your handling code here:
        adminPanel.removeAll();
        adminPanel.repaint();
        adminPanel.revalidate();

        adminPanel.add(listLapak);
        adminPanel.repaint();
        adminPanel.revalidate();
        
        tc.loadLapak();
        tc.showLapak();
    }//GEN-LAST:event_btnListLapakActionPerformed

    private void btnListPenyewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListPenyewaActionPerformed
        // TODO add your handling code here:
        adminPanel.removeAll();
        adminPanel.repaint();
        adminPanel.revalidate();

        adminPanel.add(listPenyewa);
        adminPanel.repaint();
        adminPanel.revalidate();
        
        tc.loadPenyewa();
        tc.showPenyewa();
    }//GEN-LAST:event_btnListPenyewaActionPerformed

    private void btnListTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListTransaksiActionPerformed
        // TODO add your handling code here:
        adminPanel.removeAll();
        adminPanel.repaint();
        adminPanel.revalidate();

        adminPanel.add(listTransaksi);
        adminPanel.repaint();
        adminPanel.revalidate();
        
        tc.loadTransaksi();
        tc.showTransaksi();
    }//GEN-LAST:event_btnListTransaksiActionPerformed

    private void btnPengaturan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengaturan1ActionPerformed
        // TODO add your handling code here:
        dispose();
        ViewLogin login = new ViewLogin();
        login.setVisible(true);
    }//GEN-LAST:event_btnPengaturan1ActionPerformed

    private void cbLokasiLapakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLokasiLapakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLokasiLapakActionPerformed
    
    private void btTambahLapakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTambahLapakActionPerformed
        String lokasi = cbLokasiLapak.getSelectedItem().toString();
        String uPanjang = tfUkuranPanjang.getText();
        String uLebar = tfUkuranLebar.getText();
        String ukuran = uPanjang + " x " + uLebar;
        String hargaSewa = tfHargaLapak.getText();
        if(lokasi.equals("") || ukuran.equals("") || hargaSewa.equals("")){
            JOptionPane.showMessageDialog(this, "Isi field yang masih kosong !");
        }else{
            fc.tambahLapak(ukuran, lokasi, hargaSewa);
            tc.loadLapak();
            tc.showLapak();
        }
    }//GEN-LAST:event_btTambahLapakActionPerformed

    private void etcbLokasiLapakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etcbLokasiLapakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etcbLokasiLapakActionPerformed

    private void btUbahLapakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUbahLapakActionPerformed
        int id = 0;
        try{
        int selectedRow = tbListLapak.getSelectedRow();
        id = Integer.parseInt(tc.getModelLapak().getValueAt(selectedRow, 0).toString());
        String lokasi = etcbLokasiLapak.getSelectedItem().toString();
        String uPanjang = tfEditPanjang.getText();
        String uLebar = tfEditLebar.getText();
        String ukuran = uPanjang + " x " + uLebar;
        String hargaSewa = tfEditHarga.getText();
        if(lokasi.equals("") || ukuran.equals("") || hargaSewa.equals("") || id == 0){
            JOptionPane.showMessageDialog(this, "Isi field yang masih kosong !");
        }else{
           fc.ubahDataLapak(id, ukuran, lokasi, hargaSewa);
           JOptionPane.showMessageDialog(this, "Data berhasil diubah");
           tc.loadLapak();
           tc.showLapak();
        }
        }catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(this, "Pilih lapak yang ingin diubah");
        }
    }//GEN-LAST:event_btUbahLapakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminPanel;
    private javax.swing.JButton btTambahLapak;
    private javax.swing.JButton btUbahLapak;
    private javax.swing.JButton btnListLapak;
    private javax.swing.JButton btnListPenyewa;
    private javax.swing.JButton btnListToko;
    private javax.swing.JButton btnListTransaksi;
    private javax.swing.JButton btnPengaturan1;
    private javax.swing.JComboBox<String> cbLokasiLapak;
    private javax.swing.JPanel editLapak;
    private javax.swing.JComboBox<String> etcbLokasiLapak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPanel listLapak;
    private javax.swing.JPanel listPenyewa;
    private javax.swing.JPanel listToko;
    private javax.swing.JPanel listTransaksi;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel tambahLapak;
    private javax.swing.JTable tbListLapak;
    private javax.swing.JTable tbListPenyewa;
    private javax.swing.JTable tbListToko;
    private javax.swing.JTable tbListTransaksi;
    private javax.swing.JTextField tfEditHarga;
    private javax.swing.JTextField tfEditLebar;
    private javax.swing.JTextField tfEditPanjang;
    private javax.swing.JTextField tfHargaLapak;
    private javax.swing.JTextField tfUkuranLebar;
    private javax.swing.JTextField tfUkuranPanjang;
    // End of variables declaration//GEN-END:variables
}
